name:                AdventOfCode2018
version:             0.1.0.0
github:              "lawrencetaylor/AdventOfCode2018"
license:             BSD3
author:              "Lawrence Taylor"
maintainer:          ""
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lawrencetaylor/AdventOfCode2018#readme>

dependencies:
- base >= 4.7 && < 5
- text
- acme-missiles
- parsec
- parsec3-numbers
- filepath
- directory
- containers
- ghc-prim

library:
  source-dirs: src

executables:
  AdventOfCode2018-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2018

# tests:
#   AdventOfCode2018-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - AdventOfCode2018
